### PR TITLE
fixes align behavior in button timeline

### LINKED ISSUE #39: fix align behavior in button timeline
### Expected Behavior
`align` should change the vertical alignment of the timeline, regardless of "buttons" or "ticks" behavior. Timelines should always be horizontally centered (for now)

### Current Behavior
This one is my fault, I told you to make `align` change the horizontal alignment of the button timeline.

### Steps to Reproduce (for bugs)
http://jsfiddle.net/cfgyorpd/1/

### Your Environment

* Browser Name: Chrome
* Operating System and Version: macOS Mojave

### PR DESCRIPTION
**Pull request by cnavarreteliz**
closes #39 

### Description

For to solve this bug, I calculated the value of `y` position in button timeline.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### CODE REVIEW

File: src/Timeline.js [hunk 1]
```diff
@@ -369,6 +374,16 @@ function() {
...
   }
 
+  /**
+      @memberof Timeline
+      @desc If *value* is specified, toggles the horizontal alignment of the button timeline. Accepted values are `"start"`, `"middle"` and `"end"`. If *value* is not specified, returns the current button value.
+      @param {String} [*value* = "middle"]
+      @chainable
+  */
+  buttonAlign(_) {
+    return arguments.length ? (this._buttonBehavior = _, this) : this._buttonBehavior;
```
Comment (davelandry) [inline src/Timeline.js]: this should be setting `this._buttonAlign`

**Review by davelandry — CHANGES_REQUESTED** [review]
Great work on this PR @cnavarreteliz. I like the addition of a `buttonAlign` method, but it's not working! Please make sure to test new methods before submitting a PR.
