### PR TITLE
solves bug using timeline in viz

### LINKED ISSUE #19: define labels based on defined ticks
If the user has specific `ticks` for the timeline, use those for the `labels` as well.

```js
if (this._ticks) this.labels(this._ticks);
```

### LINKED ISSUE #94: new version of d3plus-timeline breaks viz
@cnavarreteliz clone this repo, do an `npm i`, and check out this example:

```js
new d3plus.Viz()
  .data([
    {"year": 2010, "id": "alpha", "value": 20},
    {"year": 2011, "id": "beta", "value": 20},
    {"year": 2013, "id": "gamma", "value": 40}
  ])
  .time("year")
  .render();
```

### PR DESCRIPTION
**Pull request by cnavarreteliz**
(closes d3plus/d3plus-viz#94)
(closes #19)

### Description
The bug was caused because the current behavior in button timeline only accepted correlatives values. For to solve it, I set the buttonBehavior with ordinal scale, and I rewrite the logic behind selections and domains using buttons. 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] I have documented all new methods.
- [ ] I have written tests for all new methods/functionality.
- [ ] I have written examples for all new methods/functionality.

### CODE REVIEW

File: src/Timeline.js [hunk 1]
```diff
@@ -25,6 +25,7 @@ export default class Timeline extends Axis {
   constructor() {
 
     super();
+    this._align = () => this._buttonBehaviorCurrent === "buttons" ? "middle" : "start";
```
Comment (davelandry) [inline src/Timeline.js]: why is this here? shouldn't this just be the default d3plus-axis `"middle"` for all button types?

File: src/Timeline.js [hunk 2]
```diff
@@ -74,24 +75,37 @@ export default class Timeline extends Axis {
...
-        : this._buttonBehaviorCurrent === "buttons" 
-          ? [event.sourceEvent.offsetX, event.sourceEvent.offsetX] : [event.selection[0], event.selection[0]])
-        .map(this._d3Scale.invert)
-        .map(Number);
-
-      const ticks = this._availableTicks.map(Number);
-
-      domain[0] = date(closest(domain[0], ticks));
-      domain[1] = date(closest(domain[1], ticks));
+      const domain = this._buttonBehaviorCurrent === "ticks"
```
Comment (davelandry) [inline src/Timeline.js]: this logic of determining the `pixelDomain` is getting rather large, and being used in 3 places. move this code out of these 3 functions into it's on method of the class called `_pixelDomain`

File: src/Timeline.js [hunk 3]
```diff
@@ -74,24 +75,37 @@ export default class Timeline extends Axis {
...
+        domain[0] = closest(domain[0], ticks);
+        domain[1] = closest(domain[1], ticks);
+      }
 
       const single = +domain[0] === +domain[1];
+      this._selection = this._buttonBehaviorCurrent === "ticks" 
+        ? single ? domain[0] : domain 
+        : single 
+          ? new Date(this._availableTicks[ticks.indexOf(domain[0])], 0, 1) 
+          : [new Date(this._availableTicks[ticks.indexOf(domain[0])], 0, 1), new Date(this._availableTicks[ticks.indexOf(domain[1])], 0, 1)];
```
Comment (davelandry) [inline src/Timeline.js]: why are you using the JavaScript `Date` and not the d3plus `date` function? You can probably just use `date` and condense all of this code.

**Review by davelandry — CHANGES_REQUESTED** [review]

File: src/Timeline.js [hunk 4]
```diff
@@ -74,25 +75,28 @@ export default class Timeline extends Axis {
...
-          ? [event.sourceEvent.offsetX, event.sourceEvent.offsetX] : [event.selection[0], event.selection[0]])
-        .map(this._d3Scale.invert)
-        .map(Number);
+      const domain = this._buttonBehaviorCurrent === "ticks"
+        ? (this._brushing 
+          ? event.selection 
+          : [event.sourceEvent.offsetX, event.sourceEvent.offsetX]).map(this._d3Scale.invert).map(Number) 
+        : (this._brushing 
+          ? selection
+          : [event.sourceEvent.offsetX, event.sourceEvent.offsetX]).map(Number);
```
Comment (davelandry) [inline src/Timeline.js]: can we move these `domain` and `ticks` variables into the updateDomain function as well?

**Review by davelandry — CHANGES_REQUESTED** [review]

File: src/Timeline.js (hunk 4 above)
Comment (cnavarreteliz) [reply src/Timeline.js]: I tried it yesterday and I had problems, because in every event the calcule of the domain is different, and `ticks` variable is used for to calculate `this._selection` when buttonBehavior is `button`.

Comment (davelandry) [reply src/Timeline.js]: The only difference in the `domain` variables that I see is in the `_brushBrush` event where you override the `selection` to be used. Could that logic be applied directly in the `_updateDomain` function? If not, could it be applied to the domain after running the `_updateDomain` function? You are currently returning `domain` from that function, but are not catching it (just updating the domain in place). I could see something like this:

```js
const domain = this._updateDomain(event);
```

Additionally, you can move the `ticks` variable into that function (you already have it in there!) and just return that as well as part of an Object that you can destructure:

```js
return {domain, ticks};
```

```js
const {domain, ticks} = this._updateDomain(event);
```

**Review by davelandry — CHANGES_REQUESTED** [review]

File: src/Timeline.js [hunk 5]
```diff
@@ -25,6 +25,7 @@ export default class Timeline extends Axis {
   constructor() {
 
     super();
+    this._align = "middle";
```
Comment (davelandry) [inline src/Timeline.js]: this is duplicating the default inside of `Axis`, so it can be removed.

**Review by davelandry — CHANGES_REQUESTED** [review]
Found two small bugs with the latest build:

1. On non-brushing timelines, the padding/spacing is off (look at the highlighted area):

spacing

2. On brushing timelines, the selection is wrong if you start brushing on the right side of the button:

brushing

**Comment by cnavarreteliz** [comment]
I couldn't reproduce the first bug in my laptop.

I identified the root cause of the second bug, and I'm working on it!

**Comment by davelandry** [comment]
What browser are you using? I'm able to see the first bug in both Chrome and Safari. Can you post a screenshot of what you see?

**Comment by cnavarreteliz** [comment]
d3plusbug

@davelandry I tested in Safari and Chrome without problems.

*Google Chrome | 68.0.3440.106 (Build oficial) (64 bits)*

**Review by davelandry — APPROVED** [review]

**Comment by davelandry** [comment]
@cnavarreteliz I just did a release, can you check to see if you can see the bug with the production build? https://d3plus.org/js/d3plus-timeline.v0.4.full.min.js
